### ISSUE TITLE
Formatting removes "else" from Razor View

### ISSUE THREAD

**Issue by Wonovan** [madskristensen/CodeCleanupOnSave#2]
In VS 2019, I have code like the following in a Razor view. When CodeCleanupOnSave is enabled this:

```
@if (HttpContext.Current.Request.IsLocal)
{
    @Scripts.Render("~/Scripts/123.js")
}
else
{
    @Scripts.Render("~/Scripts/123.min.js")
}
```

turns into:

```
@if (HttpContext.Current.Request.IsLocal)
{
    @Scripts.Render("~/Scripts/123.js")
    {
    @Scripts.Render("~/Scripts/123.min.js")
}
```

With CodeCleanupOnSave disabled, VS doesn't do it when I save nor when I kit Control-K-D to apply formatting.

**Comment by madskristensen** [comment]
I cannot reproduce the issue. I'm using Visual Studio 2019 version 16.1 Preview. It might have been fixed in that version. Do you have the latest preview release by chance?

**Comment by Wonovan** [comment]
I just tried in Visual Studio 2019 version 16.1.0 Preview 2 and it did **not** occur.

**Comment by madskristensen** [comment]
Awesome. Thanks for testing
