### ISSUE TITLE
Bad behavior when saving a file that is not loaded in solution

### ISSUE THREAD

**Issue by bosquig** [madskristensen/CodeCleanupOnSave#4]
Hello,

Whenever I make changes to a file that is not loaded in the current solution, the code cleanup executes but removes mandatory usings as you can see in the following gif :

![codecleanup](https://user-images.githubusercontent.com/16578090/58858781-a311ef00-86a8-11e9-9999-d77207820b52.gif)

Is there way to prevent the code cleanup from executing on save when the file is not loaded in the current solution ?

Thanks in advance.

**Comment by madskristensen** [comment]
I can use this code to find the filename, and then use the DTE to ask if the file is part of the solution

```c#
if (TextBuffer.Properties.TryGetProperty(typeof(ITextDocument), out ITextDocument textDoc))
{
    return textDoc;
}
```
